

# =====================================================
# ğŸ“Œ GRAVITY â€” Site config (Material for MkDocs)
# =====================================================
site_name: Gravity-Engineering intelligent attraction
site_description: Engineering intelligent attraction
site_author: Sana Ijlal Shahrukh
site_url: https://www.yourportfolio.com

# =====================================================
# ğŸ§­ NAV (Dropdown like â€œServicesâ€)
# =====================================================
nav:
  - Home: index.md
  - Projects: projects.md
  - Blogs: blogs.md
  - Skills: skills.md
  # - Services:
  #     - All Services: services/index.md
  #     - Python: services/python.md
  #     - AI/ML: services/ai-ml.md
  #     - Data/Analytics: services/data.md
  #     - Guides: services/guides.md
  - Resume: resume.md
  - About Gravity: about.md

theme:
  name: material
  logo: images/gravity-logo.png
  favicon: images/gravity-favicon.png

  palette:
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight

plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.superfences
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sanaijlal
      name: "ğŸ™ GitHub"
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sana-ijlal-shahrukh-558b8286/
      name: "ğŸ’¼ LinkedIn"
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/sanaijlal?s=11
      name: "ğŸ¦ X"
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/sanaijlal/
      name: "ğŸ“¸ Instagram"

    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/share/1DXp5T3JRV/?mibextid=wwXIfr
      name: "ğŸ“˜ Facebook"
     

    - icon: fontawesome/solid/envelope
      link: mailto:sanahyder@gmail.com
      name: "âœ‰ï¸ Email"
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@SanaHKhan-is8bq  
      name: "â–¶ï¸ YouTube"
    - icon: simple/googlescholar
      link: https://scholar.google.com/citations?user=uICtX4wAAAAJ&hl=en
      name: "ğŸ“ Google Scholar"



  

extra_css:
  - styles/extra.css

copyright: |
  Â© 2026 Gravity â€” Engineering intelligent attraction by Sana Ijlal Shahrukh

 

 
